name: Deployment

on:
    push:
        branches:
            - main

jobs:
    deploy:
        name: Deploy
        runs-on: ubuntu-22.04

        steps:
            - name: checkout code
              uses: actions/checkout@v4.1.1
            - name: deploy to vercel
              uses: amondnet/vercel-action@v25.1.1
              with:
                  github-commit: false
                  vercel-args: --prod
                  vercel-token: ${{ secrets.VERCEL_TOKEN }}
                  vercel-org-id: ${{ secrets.VERCEL_SCOPE }}
                  vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
                  scope: ${{ secrets.VERCEL_SCOPE }}
